version: '3.9'

services:

  backend:
    container_name: rental-backend
    build:
      context: ./ms-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    container_name: rental-db
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rental

  email-service:
    container_name: rental-email-service
    build:
      context: ./ms-email
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"

  nginx:
    container_name: rental-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge
