version: '3.9'

networks:
  rental-network:
    driver: bridge

services:

  nginx:
    container_name: rental-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rental-network

  backend:
    container_name: rental-backend
    build:
      context: ./ms-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rental-db:5432/rental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - rental-network

  postgres:
    container_name: rental-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rental
    networks:
      - rental-network

  email-service:
    container_name: rental-email-service
    build:
      context: ms-mail
      dockerfile: Dockerfile
    restart: always
    networks:
      - rental-network
