version: '3.9'

networks:
  rental-network:
    driver: bridge

services:

  nginx:
    container_name: rental-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - rental-network

  backend1:
    container_name: rental-backend1
    build:
      context: ./ms-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - rental-network

  backend2:
    container_name: rental-backend2
    build:
      context: ./ms-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - rental-network

  mysql:
    container_name: rental-db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rental
    networks:
      - rental-network

  email-service:
    container_name: rental-email-service
    build:
      context: ./ms-email
      dockerfile: Dockerfile
    restart: always
    networks:
      - rental-network
